### ISSUE TITLE
YouTubePlayer released

### ISSUE THREAD

**Issue by bhavsar-dhara** [codeforboston/conversations#28]
`07-31 20:54:41.812 19376-19376/org.aashiyaan E/ViewRootImpl: sendUserActionEvent() returned.
    sendUserActionEvent() returned.
07-31 20:54:41.813 19376-19376/org.aashiyaan E/ViewRootImpl: sendUserActionEvent() returned.
07-31 20:54:42.029 19376-19376/org.aashiyaan E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.aashiyaan, PID: 19376
    java.lang.IllegalStateException: This YouTubePlayer has been released
        at kit.a(SourceFile:106)
        at kit.l(SourceFile:235)
        at akgr.onTransact(SourceFile:45)
        at android.os.Binder.transact(Binder.java:612)
        at com.google.android.youtube.player.internal.d$a$a.a(Unknown Source:18)
        at com.google.android.youtube.player.internal.s.play(Unknown Source:2)
        at com.inprogress.reactnativeyoutube.YouTubePlayerController$1.run(YouTubePlayerController.java:315)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by bhavsar-dhara** [comment]
> 07-31 21:32:36.750 25312-25312/org.aashiyaan E/unknown:ViewManager: Error while updating prop videoId
>     java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
>         at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
>         at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:122)
>         at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95)
>         at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821)
>         at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
>         at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
>         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988)
>         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
>         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
>         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:723)
>         at android.view.Choreographer.doFrame(Choreographer.java:655)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
>         at android.os.Handler.handleCallback(Handler.java:789)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6938)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
>      Caused by: java.lang.IllegalStateException: This YouTubePlayer has been released
>         at kit.a(SourceFile:106)
>         at kit.b(SourceFile:220)
>         at akgr.onTransact(SourceFile:18)
>         at android.os.Binder.transact(Binder.java:612)
>         at com.google.android.youtube.player.internal.d$a$a.b(Unknown Source:23)
>         at com.google.android.youtube.player.internal.s.loadVideo(Unknown Source:2)
>         at com.google.android.youtube.player.internal.s.loadVideo(Unknown Source:1)
>         at com.inprogress.reactnativeyoutube.YouTubePlayerController.loadVideo(YouTubePlayerController.java:207)
>         at com.inprogress.reactnativeyoutube.YouTubePlayerController.setVideoId(YouTubePlayerController.java:347)
>         at com.inprogress.reactnativeyoutube.YouTubeView.setVideoId(YouTubeView.java:165)
>         at com.inprogress.reactnativeyoutube.YouTubeManager.setPropVideoId(YouTubeManager.java:110)
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80) 
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
>         at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32) 
>         at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:122) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821) 
>         at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928) 
>         at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988) 
>         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
>         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134) 
>         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105) 
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
>         at android.view.Choreographer.doCallbacks(Choreographer.java:723) 
>         at android.view.Choreographer.doFrame(Choreographer.java:655) 
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
>         at android.os.Handler.handleCallback(Handler.java:789) 
>         at android.os.Handler.dispatchMessage(Handler.java:98) 
>         at android.os.Looper.loop(Looper.java:164) 
>         at android.app.ActivityThread.main(ActivityThread.java:6938) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
> 07-31 21:32:36.752 25312-25312/org.aashiyaan E/unknown:ReactNative: Exception in native call
>     com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'videoId' of a view managed by: ReactYouTube
>         at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:92)
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
>         at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
>         at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:122)
>         at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95)
>         at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821)
>         at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
>         at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
>         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988)
>         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
>         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
>         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:723)
>         at android.view.Choreographer.doFrame(Choreographer.java:655)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
>         at android.os.Handler.handleCallback(Handler.java:789)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6938)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
>      Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
>         at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32) 
>         at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:122) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821) 
>         at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928) 
>         at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988) 
>         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
>         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134) 
>         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105) 
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
>         at android.view.Choreographer.doCallbacks(Choreographer.java:723) 
>         at android.view.Choreographer.doFrame(Choreographer.java:655) 
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
>         at android.os.Handler.handleCallback(Handler.java:789) 
>         at android.os.Handler.dispatchMessage(Handler.java:98) 
>         at android.os.Looper.loop(Looper.java:164) 
>         at android.app.ActivityThread.main(ActivityThread.java:6938) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
>      Caused by: java.lang.IllegalStateException: This YouTubePlayer has been released
>         at kit.a(SourceFile:106)
>         at kit.b(SourceFile:220)
>         at akgr.onTransact(SourceFile:18)
>         at android.os.Binder.transact(Binder.java:612)
>         at com.google.android.youtube.player.internal.d$a$a.b(Unknown Source:23)
>         at com.google.android.youtube.player.internal.s.loadVideo(Unknown Source:2)
>         at com.google.android.youtube.player.internal.s.loadVideo(Unknown Source:1)
>         at com.inprogress.reactnativeyoutube.YouTubePlayerController.loadVideo(YouTubePlayerController.java:207)
>         at com.inprogress.reactnativeyoutube.YouTubePlayerController.setVideoId(YouTubePlayerController.java:347)
>         at com.inprogress.reactnativeyoutube.YouTubeView.setVideoId(YouTubeView.java:165)
>         at com.inprogress.reactnativeyoutube.YouTubeManager.setPropVideoId(YouTubeManager.java:110)
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80) 
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
>         at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32) 
>         at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:122) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821) 
>         at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928) 
>         at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988) 
>         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
>         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134) 
>         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105) 
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
>         at android.view.Choreographer.doCallbacks(Choreographer.java:723) 
>         at android.view.Choreographer.doFrame(Choreographer.java:655) 
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
>         at android.os.Handler.handleCallback(Handler.java:789) 
>         at android.os.Handler.dispatchMessage(Handler.java:98) 
>         at android.os.Looper.loop(Looper.java:164) 
>         at android.app.ActivityThread.main(ActivityThread.java:6938) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
>
